root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 500  
  exclude_dir = ["assets", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]

[color]
  build = "yellow"

[log]
  main_only = false

[misc]
  clean_on_exit = false

[screen]
  keep_scroll = true
