definitions:
  dtos.ResponseUserID:
    properties:
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User avatar
        in: formData
        name: avatar
        type: file
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseUserID'
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
